### ISSUE TITLE
Context menu in theme color

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-ui-contextmenu#11]
When another theme is being supplied to the dashboard, we should show the context menu in the theme colors ...

**Comment by bartbutenaers** [comment]
I think we can use this recent [feature](https://discourse.nodered.org/t/how-to-retrieve-site-sizes-from-my-custom-node-source-code/9681/7?u=bartbutenaers) since dashboard version xx.

**Comment by hotNipi** [comment]
With theme colors and custom colors, the hover is not working. With inline styles applied to the elements the  css :hover state becomes unusable.

**Comment by bartbutenaers** [comment]
Hey @hotNipi,
Do you have a proposal how we can solve that, based on your experience?
Thanks in advance!
Bart

**Comment by hotNipi** [comment]
Most probably the best solution is to use css variables and apply proper value based on user choice. I'm not an expert in CSS so there might be better solutions. 
Side question - why you are offering the browser defaults as option? 
I'd suggest to have dashboard values as default and user choice (one by one override) Makes css handling much easier.

**Comment by Steve-Mcl** [comment]
So the issues I see are...
* old dashboard installed + theme selected == call to `ui.getTheme();` fails and the menu doesn't work at all!
* Cstom mode - hover stops working due to setting background directly in style (doing this removes  ':hover'

What I've done...
1. Dynamically generate additional styles & add to DOM based on selection of `custom` or `theme`
1. Calculate missing colors (i.e. what color would disabled text be if text is red?  Grey? Light Red? Dark Red?  - What I ended up doing is blending 50% from textColor towards background color
1. Add the new class name to the parent div to use new colors

Demo...
![2019-10-16_11-14-35](https://user-images.githubusercontent.com/44235289/66910384-61a23080-f006-11e9-9188-1ddd1c75da08.gif)

**Comment by hotNipi** [comment]
old dashboard installed + theme selected == call to ui.getTheme() <- how old dashboard?
If I remember correctly, it should be available since v2.15.0

**Comment by Steve-Mcl** [comment]
> old dashboard installed + theme selected == call to ui.getTheme() <- how old dashboard?
> If I remember correctly, it should be available since v2.15.0

Cant remember, maybe 2.12?  But definitely prior to 2.15.0 on one of my dev machines :fearful: 

Slight update to choice of dashboard colours due to issue on light theme.
This is whats now in repo...


### Built in dark theme  (menu1=custom, menu2=theme, menu2=native)
![](https://discourse-cloud-file-uploads.s3.dualstack.us-west-2.amazonaws.com/business6/uploads/nodered/original/2X/8/807b79a28ae9796c2a17b78f9f50244e8a896f98.gif)




### Built in light theme  (menu1=custom, menu2=theme, menu2=native)

![](https://discourse-cloud-file-uploads.s3.dualstack.us-west-2.amazonaws.com/business6/uploads/nodered/original/2X/c/c382016699e09f5bf84bae449dc85dd910ca9496.gif)

**Comment by Steve-Mcl** [comment]
I'm closing this now as I believe it to be complete. Re-open if necessary.
