### ISSUE TITLE
[FR] Autohide Context Menu without mouse leave

### ISSUE THREAD

**Issue by Hypnos3** [bartbutenaers/node-red-contrib-ui-contextmenu#22]
It seems to be that currently the Timer for Auto hide only starts when the mouse leaves the context menu. If the mouse never enters the context menu, it will not be auto hidden.

Please implement an AutoHide if never entered the context menu. In my useCase I Have a Button on the Dashboard which opens the context menu and it should be closed automatically if no selection is done within a couple of seconds. (This is used on a Touch screen.)
Currently if anybody press the button to open the context manu, it appears and never will be hidden.

Additionally the context manu will sometimes be opened when the dashboards loads. In such case the context menu also never will be hidden.

**Comment by bartbutenaers** [comment]
Hi @Hypnos3,

I have created a branch "_autohide-options_" with extra auto-hide options.

Currently we had a fixed flow to activate the auto-hide timer, but that seems not to be sufficient in all cases (like yours).  So I have added three separate checkboxes, to make sure that everybody can  achieve the behaviour they expect:

![image](https://user-images.githubusercontent.com/14224149/73615550-1a699b00-4609-11ea-8311-9bd8fd4d1770.png)

The above two checkboxes are enabled by default, because I assume that is the most used behaviour...  I assume you need to select all 3 checkboxes?

Does this makes sense to you?

Would be nice if you could test it and give some feedback!
You can install this branch directly from my Github repository:
```
npm install bartbutenaers/node-red-contrib-ui-contextmenu#autohide-options
```

Bart

**Comment by Hypnos3** [comment]
Hi Bart,

Thank you, that makes sense to me
I will test tomorrow.
Thank you!

**Comment by Hypnos3** [comment]
Thank you very much and sorry for the late response. The new option works as desired!

**Comment by bartbutenaers** [comment]
Hey @Hypnos3,
Thanks for your feedback.  
Version **1.0.7** has been published on NPM
