### ISSUE TITLE
Browser's contextmenu

### ISSUE THREAD

**Issue by andreypopov** [bartbutenaers/node-red-contrib-ui-contextmenu#29]
Any ideas how to remove default menus?

![2021-03-09_18-45-01](https://user-images.githubusercontent.com/1624839/110497556-9c2ed080-8107-11eb-9db6-a8799b7ec568.png)

![2021-03-09_18-45-50](https://user-images.githubusercontent.com/1624839/110497644-b10b6400-8107-11eb-9db1-39e8e88a848c.png)

**Comment by bartbutenaers** [comment]
Hi Andrey,
Due to a surgery, unfortunately I cannot develop for a few months :-(
Can only provide you some tips via my smartphone...
In which circumstances doest that popup occur?

**Comment by andreypopov** [comment]
![2021-03-09 20 54 15](https://user-images.githubusercontent.com/1624839/110515747-c6898980-8119-11eb-9ffc-77dedf0f4841.gif)

**Comment by bartbutenaers** [comment]
@andreypopov,
Did your template node solve the problem?  Because I see that Dave suggests the same solution [here](https://discourse.nodered.org/t/how-to-disable-right-click-contect-memu/42484/2?u=bartbutenaers).
If so, a template node might be a better solution, instead of adding that code snippet into this node   Because it is related to the ENTIRE dashboard.  Any thoughts?

**Comment by andreypopov** [comment]
I tried this solution, also doesnt work. It works everywhere except svg-contexmenu

**Comment by andreypopov** [comment]
Everything was broken after some updates, now I can't open nested menu, it hides immediately...

**Comment by bartbutenaers** [comment]
Hi @andreypopov,
Am I correct that this is another is another issue, not related to the origonal problem?  If so, it is easier for me (to follow up) if you register a new issue.  Because I have already a long list of other issues that I need to process after my revalidation.
And can you provide some extra info: is it on all devices/browsers, a simple example flow, ...  That makes it easier for me to keep supporting everybody in my limited spare time...

**Comment by andreypopov** [comment]
[Pull request](https://github.com/bartbutenaers/node-red-contrib-ui-svg/pull/93)

**Comment by bartbutenaers** [comment]
Pull request published via Svg node version _**2.2.2**_
